Repository puppetlabs/puppetdb, pull requests merged in 2019-09, with the labels that each got.

#3055 (PDB-2634) Hash projection for (some) json fields
  documentation/api/query/examples-pql.markdown
  documentation/api/query/v4/ast.markdown
  src/puppetlabs/puppetdb/jdbc.clj
  src/puppetlabs/puppetdb/query/resources.clj
  src/puppetlabs/puppetdb/query_eng/engine.clj
  test/puppetlabs/puppetdb/http/inventory_test.clj
  test/puppetlabs/puppetdb/http/resources_test.clj
  test/puppetlabs/puppetdb/query_eng_test.clj
Labels: higher priority, please review

#3082 (maint) Update docker ssl volume
  docker/docker-compose.yml
  docker/puppetdb/Dockerfile
  docker/puppetdb/conf.d/config.conf
  docker/puppetdb/conf.d/jetty.ini
  docker/puppetdb/docker-entrypoint.d/30-configure-ssl.sh
  docker/puppetdb/logback.xml
  docker/puppetdb/request-logging.xml
  docker/puppetdb/ssl-setup.sh
Labels: don't merge, work in progress

#3074 (PDB-4504) Use batched inserts for add-resource-events-pk
  src/puppetlabs/puppetdb/scf/migrate.clj
  test/puppetlabs/puppetdb/scf/migrate_test.clj
Labels: higher priority
